CALENDAR_BOUNDARY = '---------------------------41566770301618672087425875231'
NEWS_BOUNDARY = '---------------------------48222048032047603611657549096'

CALENDAR_CONTENT_TYPE = f'multipart/form-data; boundary={CALENDAR_BOUNDARY}'
NEWS_CONTENT_TYPE = f'multipart/form-data; boundary={NEWS_BOUNDARY}'

NEWS_PAYLOADS = {
    'latest': (
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="securitytoken"\r\n'
        '\r\n'
        'guest\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="do"\r\n'
        '\r\n'
        'saveoptions\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="setdefault"\r\n'
        '\r\n'
        'no\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="ignoreinput"\r\n'
        '\r\n'
        'no\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[News_newsLeft1][idSuffix]"\r\n'
        '\r\n'
        '{}\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[News_newsLeft1][_flexForm_]"\r\n'
        '\r\n'
        'flexForm\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[News_newsLeft1][modelData]"\r\n'
        '\r\n'
        'eyJwYV9sYXlvdXRfaWQiOiJuZXdzIiwicGFfY29tcG9uZW50X2lkIjoiTmV3c0xlZnRPbmUiLCJwYV9jb250cm9scyI6Im5ld3N8TmV3c0xlZnRPbmUiLCJwYV9pbmplY3RyZXZlcnNlIjpmYWxzZSwicGFfaGFyZGluamVjdGlvbiI6ZmFsc2UsInBhX2luamVjdGF0IjpmYWxzZX0=\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[News_newsLeft1][stream][]"\r\n'
        '\r\n'
        '1\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[News_newsLeft1][news]"\r\n'
        '\r\n'
        'all\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[News_newsLeft1][format]"\r\n'
        '\r\n'
        'headline\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[News_newsLeft1][items]"\r\n'
        '\r\n'
        '15\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[News_newsLeft1][sort]"\r\n'
        '\r\n'
        'latest\r\n'
        f'--{NEWS_BOUNDARY}--\r\n'
    ),
    'hottest': (
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="securitytoken"\r\n'
        '\r\n'
        'guest\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="do"\r\n'
        '\r\n'
        'saveoptions\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="setdefault"\r\n'
        '\r\n'
        'no\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="ignoreinput"\r\n'
        '\r\n'
        'no\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[News_newsRight1][idSuffix]"\r\n'
        '\r\n'
        '{}\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[News_newsRight1][_flexForm_]"\r\n'
        '\r\n'
        'flexForm\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[News_newsRight1][modelData]"\r\n'
        '\r\n'
        'eyJwYV9sYXlvdXRfaWQiOiJuZXdzIiwicGFfY29tcG9uZW50X2lkIjoiTmV3c1JpZ2h0T25lIiwicGFfY29udHJvbHMiOiJuZXdzfE5ld3NSaWdodE9uZSIsInBhX2luamVjdHJldmVyc2UiOmZhbHNlLCJwYV9oYXJkaW5qZWN0aW9uIjpmYWxzZSwicGFfaW5qZWN0YXQiOmZhbHNlfQ==\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[News_newsRight1][news]"\r\n'
        '\r\n'
        'all\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[News_newsRight1][format]"\r\n'
        '\r\n'
        'large\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[News_newsRight1][items]"\r\n'
        '\r\n'
        '3\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[News_newsRight1][sort]"\r\n'
        '\r\n'
        'hottest\r\n'
        f'--{NEWS_BOUNDARY}--\r\n'
    ),
    'most_viewed': (
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="securitytoken"\r\n'
        '\r\n'
        'guest\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="do"\r\n'
        '\r\n'
        'saveoptions\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="setdefault"\r\n'
        '\r\n'
        'no\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="ignoreinput"\r\n'
        '\r\n'
        'no\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[News_newsRight3][idSuffix]"\r\n'
        '\r\n'
        '{}\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[News_newsRight3][_flexForm_]"\r\n'
        '\r\n'
        'flexForm\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[News_newsRight3][modelData]"\r\n'
        '\r\n'
        'eyJwYV9sYXlvdXRfaWQiOiJuZXdzIiwicGFfY29tcG9uZW50X2lkIjoiTmV3c1JpZ2h0VGhyZWUiLCJwYV9jb250cm9scyI6Im5ld3N8TmV3c1JpZ2h0VGhyZWUiLCJwYV9pbmplY3RyZXZlcnNlIjpmYWxzZSwicGFfaGFyZGluamVjdGlvbiI6ZmFsc2UsInBhX2luamVjdGF0IjpmYWxzZX0=\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[News_newsRight3][news]"\r\n'
        '\r\n'
        '8\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[News_newsRight3][format]"\r\n'
        '\r\n'
        'threads\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[News_newsRight3][items]"\r\n'
        '\r\n'
        '3\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[News_newsRight3][sort]"\r\n'
        '\r\n'
        'mostviewed\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[News_newsRight3][period]"\r\n'
        '\r\n'
        'last12h\r\n'
        f'--{NEWS_BOUNDARY}--\r\n'
    ),
    'latest_fa': (
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="securitytoken"\r\n'
        '\r\n'
        'guest\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="do"\r\n'
        '\r\n'
        'saveoptions\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="setdefault"\r\n'
        '\r\n'
        'no\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="ignoreinput"\r\n'
        '\r\n'
        'no\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[News_newsRight2][idSuffix]"\r\n'
        '\r\n'
        '{}\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[News_newsRight2][_flexForm_]"\r\n'
        '\r\n'
        'flexForm\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[News_newsRight2][modelData]"\r\n'
        '\r\n'
        'eyJwYV9sYXlvdXRfaWQiOiJuZXdzIiwicGFfY29tcG9uZW50X2lkIjoiTmV3c1JpZ2h0VHdvIiwicGFfY29udHJvbHMiOiJuZXdzfE5ld3NSaWdodFR3byIsInBhX2luamVjdHJldmVyc2UiOmZhbHNlLCJwYV9oYXJkaW5qZWN0aW9uIjpmYWxzZSwicGFfaW5qZWN0YXQiOmZhbHNlfQ==\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[News_newsRight2][news]"\r\n'
        '\r\n'
        '107\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[News_newsRight2][format]"\r\n'
        '\r\n'
        'threads\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[News_newsRight2][items]"\r\n'
        '\r\n'
        '3\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[News_newsRight2][sort]"\r\n'
        '\r\n'
        'mostviewed\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[News_newsRight2][period]"\r\n'
        '\r\n'
        'last12h\r\n'
        f'--{NEWS_BOUNDARY}--\r\n'
    ),
    'latest_ta': (
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="securitytoken"\r\n'
        '\r\n'
        'guest\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="do"\r\n'
        '\r\n'
        'saveoptions\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="setdefault"\r\n'
        '\r\n'
        'no\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="ignoreinput"\r\n'
        '\r\n'
        'no\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[News_newsRight4][idSuffix]"\r\n'
        '\r\n'
        '{}\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[News_newsRight4][_flexForm_]"\r\n'
        '\r\n'
        'flexForm\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[News_newsRight4][modelData]"\r\n'
        '\r\n'
        'eyJwYV9sYXlvdXRfaWQiOiJuZXdzIiwicGFfY29tcG9uZW50X2lkIjoiTmV3c1JpZ2h0Rm91ciIsInBhX2NvbnRyb2xzIjoibmV3c3xOZXdzUmlnaHRGb3VyIiwicGFfaW5qZWN0cmV2ZXJzZSI6ZmFsc2UsInBhX2hhcmRpbmplY3Rpb24iOmZhbHNlLCJwYV9pbmplY3RhdCI6ZmFsc2V9\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[News_newsRight4][news]"\r\n'
        '\r\n'
        '89\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[News_newsRight4][format]"\r\n'
        '\r\n'
        'large\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[News_newsRight4][items]"\r\n'
        '\r\n'
        '2\r\n'
        f'--{NEWS_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[News_newsRight4][sort]"\r\n'
        '\r\n'
        'latest\r\n'
        f'--{NEWS_BOUNDARY}--\r\n'
    ),
}


def calendar_payload(date_str: str) -> str:
    return (
        f'--{CALENDAR_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="securitytoken"\r\n'
        '\r\n'
        'guest\r\n'
        f'--{CALENDAR_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="do"\r\n'
        '\r\n'
        'saveoptions\r\n'
        f'--{CALENDAR_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="setdefault"\r\n'
        '\r\n'
        'no\r\n'
        f'--{CALENDAR_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="ignoreinput"\r\n'
        '\r\n'
        'no\r\n'
        f'--{CALENDAR_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[Calendar_mainCalCopy1][idSuffix]"\r\n'
        '\r\n'
        '\r\n'
        f'--{CALENDAR_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[Calendar_mainCalCopy1][_flexForm_]"\r\n'
        '\r\n'
        'flexForm\r\n'
        f'--{CALENDAR_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[Calendar_mainCalCopy1][modelData]"\r\n'
        '\r\n'
        'eyJwYV9sYXlvdXRfaWQiOiJob21lcGFnZSIsInBhX2NvbXBvbmVudF9pZCI6IkNhbGVuZGFyX0NvcHkxIiwicGFfY29udHJvbHMiOiJob21lcGFnZXxDYWxlbmRhcl9Db3B5MSIsInBhX2luamVjdHJldmVyc2UiOmZhbHNlLCJwYV9oYXJkaW5qZWN0aW9uIjpmYWxzZSwicGFfaW5qZWN0YXQiOmZhbHNlLCJob21lQ2FsZW5kYXIiOnRydWUsInZpZXdpbmdUb2RheSI6ZmFsc2UsInRvZGF5RGF0ZSI6IlRPRGF5RFgiLCJ0b21vcnJvd0RhdGUiOiJUb21vcnJvd0RYWCIsInByZXZDYWxMaW5rIjoicmFuZ2U9bWF4MTYuMjAyMy1tYXkyMy4yMDIzIiwibmV4dENhbExpbmsiOiJyYW5nZT1qdW4xLjIwMjMtanVuOC4yMDIzIiwicHJldkFsdCI6Ik1heSAxNiwgMjAyMyAtIE1heSAyMiwgMjAyMyIsIm5leHRBbHQiOiJKdW4gMSwgMjAyMyAtIEp1biA3LCAyMDIzIiwibmV4dEhpZGRlbiI6ZmFsc2UsInByZXZIaWRkZW4iOmZhbHNlLCJyaWdodExpbmsiOnRydWV9\r\n'
        f'--{CALENDAR_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[Calendar_mainCalCopy1][begindate]"\r\n'
        '\r\n'
        f'{date_str}\r\n'
        f'--{CALENDAR_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[Calendar_mainCalCopy1][enddate]"\r\n'
        '\r\n'
        f'{date_str}\r\n'
        f'--{CALENDAR_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[Calendar_mainCalCopy1][calendardefault]"\r\n'
        '\r\n'
        'today\r\n'
        f'--{CALENDAR_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[Calendar_mainCalCopy1][impacts][high]"\r\n'
        '\r\n'
        'high\r\n'
        f'--{CALENDAR_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[Calendar_mainCalCopy1][impacts][medium]"\r\n'
        '\r\n'
        'medium\r\n'
        f'--{CALENDAR_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[Calendar_mainCalCopy1][_cbarray_]"\r\n'
        '\r\n'
        '1\r\n'
        f'--{CALENDAR_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[Calendar_mainCalCopy1][eventtypes][growth]"\r\n'
        '\r\n'
        'growth\r\n'
        f'--{CALENDAR_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[Calendar_mainCalCopy1][eventtypes][inflation]"\r\n'
        '\r\n'
        'inflation\r\n'
        f'--{CALENDAR_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[Calendar_mainCalCopy1][eventtypes][employment]"\r\n'
        '\r\n'
        'employment\r\n'
        f'--{CALENDAR_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[Calendar_mainCalCopy1][eventtypes][centralbank]"\r\n'
        '\r\n'
        'centralbank\r\n'
        f'--{CALENDAR_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[Calendar_mainCalCopy1][eventtypes][bonds]"\r\n'
        '\r\n'
        'bonds\r\n'
        f'--{CALENDAR_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[Calendar_mainCalCopy1][eventtypes][housing]"\r\n'
        '\r\n'
        'housing\r\n'
        f'--{CALENDAR_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[Calendar_mainCalCopy1][eventtypes][sentiment]"\r\n'
        '\r\n'
        'sentiment\r\n'
        f'--{CALENDAR_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[Calendar_mainCalCopy1][eventtypes][pmi]"\r\n'
        '\r\n'
        'pmi\r\n'
        f'--{CALENDAR_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[Calendar_mainCalCopy1][eventtypes][speeches]"\r\n'
        '\r\n'
        'speeches\r\n'
        f'--{CALENDAR_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[Calendar_mainCalCopy1][eventtypes][misc]"\r\n'
        '\r\n'
        'misc\r\n'
        f'--{CALENDAR_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[Calendar_mainCalCopy1][_cbarray_]"\r\n'
        '\r\n'
        '1\r\n'
        f'--{CALENDAR_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[Calendar_mainCalCopy1][currencies][aud]"\r\n'
        '\r\n'
        'aud\r\n'
        f'--{CALENDAR_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[Calendar_mainCalCopy1][currencies][cad]"\r\n'
        '\r\n'
        'cad\r\n'
        f'--{CALENDAR_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[Calendar_mainCalCopy1][currencies][chf]"\r\n'
        '\r\n'
        'chf\r\n'
        f'--{CALENDAR_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[Calendar_mainCalCopy1][currencies][cny]"\r\n'
        '\r\n'
        'cny\r\n'
        f'--{CALENDAR_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[Calendar_mainCalCopy1][currencies][eur]"\r\n'
        '\r\n'
        'eur\r\n'
        f'--{CALENDAR_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[Calendar_mainCalCopy1][currencies][gbp]"\r\n'
        '\r\n'
        'gbp\r\n'
        f'--{CALENDAR_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[Calendar_mainCalCopy1][currencies][jpy]"\r\n'
        '\r\n'
        'jpy\r\n'
        f'--{CALENDAR_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[Calendar_mainCalCopy1][currencies][nzd]"\r\n'
        '\r\n'
        'nzd\r\n'
        f'--{CALENDAR_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[Calendar_mainCalCopy1][currencies][usd]"\r\n'
        '\r\n'
        'usd\r\n'
        f'--{CALENDAR_BOUNDARY}\r\n'
        'Content-Disposition: form-data; name="flex[Calendar_mainCalCopy1][_cbarray_]"\r\n'
        '\r\n'
        '1\r\n'
        f'--{CALENDAR_BOUNDARY}--\r\n'
    )
